### ISSUE TITLE
Crash on launch 1.19

### ISSUE THREAD

**Issue by Tithonius** [eerussianguy/Better-Foliage#15]
Upon installation of this mod in curseforge app with forge 41.0.16 the game crashes before even showing the normal loading screen. The game crashes with exit code 1. The error is this error here:
![M09Z6NH](https://user-images.githubusercontent.com/20254673/172983375-679ab55b-1bc9-45a7-89df-95ecab4a6140.png)

Upon disabling the mod the game loads normally.

**Comment by Tithonius** [comment]
The log outputs this in console

23:37:20.706
launcher
main

Exception in thread "main" java.lang.IllegalArgumentException: task ':jar' property 'archiveVersion': Version string does not start with a number
	at java.base/java.lang.module.ModuleDescriptor$Version.<init>(ModuleDescriptor.java:1005)
	at java.base/java.lang.module.ModuleDescriptor$Version.parse(ModuleDescriptor.java:1090)
	at java.base/java.lang.module.ModuleDescriptor$Builder.version(ModuleDescriptor.java:2062)
	at MC-BOOTSTRAP/fmlloader@1.19-41.0.16/net.minecraftforge.fml.loading.moddiscovery.ModJarMetadata.descriptor(ModJarMetadata.java:72)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.jarhandling.impl.Jar.computeDescriptor(Jar.java:47)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.JarModuleFinder$JarModuleReference.<init>(JarModuleFinder.java:50)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.JarModuleFinder.lambda$new$0(JarModuleFinder.java:28)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.JarModuleFinder.<init>(JarModuleFinder.java:29)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.JarModuleFinder.of(JarModuleFinder.java:43)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.6/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.6/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.6/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.6/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.6/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.6/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
23:37:20.706
monitor
Process Monitor
Process crashed with exit code 1

**Comment by winnetrie83** [comment]
This crash also happens in the version betterfoliage-3.1.0.jar for MC 1.18.2
Forge version is 40.1.51

Just to be sure no other mods interfere, i had setup a profile with only this mod.

I would give you a crashlog but, none was generated and the Latest.log file has only 10 lines with nothing in it of interest.

I hope you don't recognize this as spam again. I'm just trying to be helpfull.

**Comment by whatthefxckstrid** [comment]
Can confirm, the same issue is happening to me on 1.18.2, mod verison betterfoliage-3.1.0.jar.

**Comment by eerussianguy** [comment]
I'll look at it... that's weird

**Comment by eerussianguy** [comment]
fixed on 1.18 and 1.19
