### ISSUE TITLE
Не удалось загрузить на сервер

### ISSUE THREAD

**Issue by JueChenChen** [eerussianguy/Better-Foliage#3]
-- Head --
Thread: main
Stacktrace:
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[arclight-forge-1.16-1.0.18.jar:arclight-1.16.5-1.0.18-32d233f] {re:mixin}
-- MOD betterfoliage --
Details:
        Mod File: [更好的树叶]betterfoliage-1.1.1.jar
        Failure message: Better Foliage (betterfoliage) encountered an error during the common_setup event phase
                java.lang.NullPointerException: Cannot set config value without assigned Config object present
        Mod Version: 1.1.1
        Mod Issue URL: https://github.com/eerussianguy/Better-Foliage/issues
        Exception message: java.lang.NullPointerException: Cannot set config value without assigned Config object present
Stacktrace:
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[arclight-forge-1.16-1.0.18.jar:arclight-1.16.5-1.0.18-32d233f] {re:mixin}
        at net.minecraftforge.common.ForgeConfigSpec$ConfigValue.set(ForgeConfigSpec.java:854) ~[forge:?] {re:classloading}
        at com.eerussianguy.betterfoliage.BetterFoliage.commonSetup(BetterFoliage.java:48) ~[betterfoliage:1.1.1] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.1] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

**Comment by eerussianguy** [comment]
Tell me if issue persists on 1.18
